language: cpp

sudo: required

cache:
  - apt
  - ccache

compiler:
  - gcc

matrix:
  global:
    - ROS_VERSION=melodic
    - UBUNTU_VERSION=ubuntu1804
    - TRAVIS_SOURCE_PATH=$(pwd)
    - NOSE_NOCAPTURE=1
    - WORKSPACE=$HOME/workspace
  include:
    - name: CUDA 10
      env:
      - CUDA=10.1.105-1
      - CUDA_SHORT=10.1
      - UBUNTU_VERSION=ubuntu1804
      dist: bionic

before_install:
  # Setup CUDA
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  # Setup ROS
  - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt install ros-$ROS_VERSION-desktop-full "ros-$ROS_VERSION-tf2-*" "ros-$ROS_VERSION-camera-info-manager*" --yes
  - sudo pip install requests
  - source /opt/ros/$ROS_VERSION/setup.bash
  - sudo rosdep init
  - rosdep update
  - source /opt/ros/$ROS_VERSION/setup.sh

  # Setup ccache
  - sudo apt-get install -y ccache
  - export PATH="/usr/lib/ccache:$PATH"
  - ccache --max-size=10G
  # Setup build dependencies.
  - sudo apt-get install autotools-dev doxygen dh-autoreconf git libgtest-dev python-catkin-tools python-pip python-git python-setuptools --yes

install:
    # Create a workspace.
  - mkdir -p $WORKSPACE/src
  - cp -r $TRAVIS_MAPLAB_SOURCE_PATH $WORKSPACE/src

script:
  - cd $WORKSPACE
  - ~/continuous_integration/run_build.sh -r --no_catkinsimple -x=$WORKSPACE/src/cuda_hello_world_catkin/share/prepare-ci


notification:
  - email: true
